driverlist=com.mysql.cj.jdbc.Driver
appender=com.p6spy.engine.spy.appender.Slf4JLogger
logMessageFormat=com.p6spy.engine.spy.appender.CustomLineFormat
customLogMessageFormat=%(executionTime)ms | %(sql)
excludecategories=info,debug,result,resultset,commit
databaseDialectDateFormat=yyyy-MM-dd HH:mm:ss
append=false